stages:
  prepare:
    cmd: python3.12 src/prepare.py data/raw data/prepared
    deps:
    - src/prepare.py
    - src/utils/seed.py
    - data/raw
    params:
    - prepare
    outs:
    - data/prepared

  train:
    cmd: python3.12 src/train.py data/prepared model
    deps:
    - src/train.py
    - src/utils/seed.py
    - data/prepared
    params:
    - train
    outs:
    - model

  evaluate:
    cmd: python3.12 src/evaluate.py model data/prepared
    deps:
    - src/evaluate.py
    - model
    metrics:
    - evaluation/metrics.json
    plots:
    - evaluation/plots/confusion_matrix.png
    - evaluation/plots/pred_preview.png
    - evaluation/plots/training_history.png