name: MLOps

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip
      
      - name: Install dependencies
        run: pip install --requirement requirements.txt
      
      - name: Install CML
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -fsSL https://raw.githubusercontent.com/iterative/cml/master/install.sh | bash
      
      - name: Login to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}'
      
      - name: Train model
        run: dvc repro --pull
      
      - name: Create CML report
        if: always()
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "# Model Performance Report" > report.md
          echo "" >> report.md
          
          if [ -f "evaluation/metrics.json" ]; then
            echo "## Model Metrics" >> report.md
            echo '```json' >> report.md
            cat evaluation/metrics.json >> report.md
            echo '```' >> report.md
            echo "" >> report.md
          fi
          
          if [ -d "evaluation/plots" ]; then
            echo "## Model Plots" >> report.md
            for plot in evaluation/plots/*.png; do
              if [ -f "$plot" ]; then
                echo "![$(basename "$plot")]($(basename "$plot"))" >> report.md
                echo "" >> report.md
              fi
            done
          fi
          
          cml comment create report.md